# Generated by Django 3.1.6 on 2021-10-25 06:32

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20211022_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.nameFile),
        ),
    ]
